# Generated by Django 5.0.4 on 2024-04-11 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('quiz_class', models.CharField(max_length=30, verbose_name='کلاس')),
                ('info', models.TextField(verbose_name='توضیحات')),
                ('score', models.IntegerField(verbose_name='امتیاز آزمون')),
                ('questions_count', models.IntegerField(verbose_name='مجموع سوالات')),
                ('time', models.IntegerField(verbose_name='زمان آزمون به دقیقه')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='طراح آزمون')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='متن سوال')),
                ('option_one', models.TextField(verbose_name='گزینه یک')),
                ('option_two', models.TextField(verbose_name='گزینه دوم')),
                ('option_three', models.TextField(verbose_name='گزینه سوم')),
                ('option_four', models.TextField(verbose_name='گزینه چهارم')),
                ('anwser', models.IntegerField(verbose_name='گزینه درست')),
                ('score', models.IntegerField(verbose_name='امتیاز')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizModule.quizmodel', verbose_name='آزمون')),
            ],
        ),
    ]
