# Generated by Django 5.0.4 on 2024-04-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizModule', '0003_quizmodel_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده/نشده'),
        ),
    ]
