# Generated by Django 5.0.4 on 2024-04-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizModule', '0004_quizmodel_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='is_random',
            field=models.BooleanField(default=False, verbose_name='سوالات شانسی هست/نیست'),
        ),
    ]
