# Generated by Django 5.0.4 on 2024-04-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizModule', '0006_remove_quizmodel_questions_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='score',
        ),
    ]
