# Generated by Django 5.0.4 on 2024-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizModule', '0008_alter_quizmodel_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='quiz_code',
            field=models.CharField(max_length=10, null=True, verbose_name='کد آزمون'),
        ),
    ]
