# Generated by Django 5.0.4 on 2024-05-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizModule', '0009_quizmodel_quiz_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='quiz_code',
            field=models.CharField(max_length=11, null=True, verbose_name='کد آزمون'),
        ),
    ]
