# Generated by Django 5.0.4 on 2024-04-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/users-profiles/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='score',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_class',
            field=models.CharField(max_length=10, null=True, verbose_name='کلاس'),
        ),
    ]
