# Generated by Django 5.0.4 on 2024-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0002_alter_usermodel_email_alter_usermodel_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='isTeacher',
            field=models.BooleanField(default=False, verbose_name='معلم هست/نیست'),
        ),
    ]
